# Generated by Django 4.2 on 2023-04-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0004_alter_profissao_options_cliente_profissao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
